### ISSUE TITLE
Issues with newer versions

### ISSUE THREAD

**Issue by pmsobrado** [chiteroman/PlayIntegrityFix#249]
I have 5 fingerprints that are working with DEV v2 and 15.2 version of this module, but not with 15.4 or 15.5. I guess recent updates removed certain compatibility with some models or ROMs.

I'm using a Xiaomi Mi 10 Pro, Android 10 / MIUI 12 (xiaomi.eu, old ROM, it should not have any xiaomi.eu recent fixes, when the ROM I'm using was launched, PI API didn't exist).

I don't know if you are intentionally removing certain compatibility for old phones or ROMs, if that's the case, it's OK, if not, I hope we can get back wider compatibility with next updates.

Looking at the telegram group, it seems more people is having this problem with newer 15.4 and 15.5 versions.

Thanks.

**Comment by imaginati0n96** [comment]
Bro i just created my account to say thank you for mentioning it!

Iam running on a MI 9 SE and now my Wallet works after downgrading to 15.2. <3

hope u never run out of Approvals :))

**Comment by chiteroman** [comment]
Can you check v15.6 ?

**Comment by pmsobrado** [comment]
Sure, testing now...

**Comment by chiteroman** [comment]
Uhh, weird.

Can you send full logcat after request an attestation (Play Integrity) ?

**Comment by pmsobrado** [comment]
Do you have a magic command to dump the full logcat? Could I send it to you privately, via Telegram or something else?

**Comment by crok** [comment]
> No integrity at all, with same FP that passes basic and device on DEV v2 and 15.2 :(

If you killed gms.unstable please wait some time to make sure the process starts correctly, even try to restart the phone and check again. I experienced the same with some ROMs on some phones.

BTW:   `logcat -d > /sdcard/logcat.txt`   this will save the whole logcat to logcat.txt in your internal storage.

**Comment by pmsobrado** [comment]
> 
> If you killed gms.unstable please wait some time to make sure the process starts correctly, even try to restart the phone and check again. I experienced the same with some ROMs on some phones.
> 
 Not sure what do you mean, for changing from DEV v2 and 15.6 module versions in this case I have to reboot the phone...

**Comment by chiteroman** [comment]
> @chiteroman I will upload two log dumps, one for DEV v2 and one for 15.6 once you tell me where to upload to you privately :)

If you don't want share them here, you can send me PM in Telegram or in XDA ^^.

**Comment by pmsobrado** [comment]
Telegram it is :)

**Comment by chiteroman** [comment]
> Goolag play services keeps crashing/closing after i updated to 15.6 for some reason and i rolledback then everything works fine, using havoc os A10, custom kernel

Can you try this? https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v15.7

**Comment by pmsobrado** [comment]
I had the force close bug with 15.4 but not 15.5 or 15.6. I tried 15.7 and no FC, and also my FP passes. I will try the others I have tomorrow or when I have the time.

What was it??

**Comment by chiteroman** [comment]
v15.7.1 should fix it: https://github.com/chiteroman/PlayIntegrityFix/releases/tag/v15.7

**Comment by isaacay** [comment]
I am also having this issue  pixel 8 pro on the qpr releases using the newest version 15.7.2 while 15.2 still works

**Comment by pmsobrado** [comment]
@chiteroman I'm afraid this buggy behaviour is back, today all my FPs gives NO_INTEGRITY, going back to PIF DEV v2 does not solve it, I checked with other user, same PIF and Magisk version, same FP, and it works for him, here are my logs:

`02-12 13:09:02.524  8825  8825 D PIF/Native: Found '__system_property_read_callback' handle at 0x7828de3d60
02-12 13:09:02.524  8825  8825 D PIF/Native: Read 7072 bytes of classes.dex
02-12 13:09:02.524  8825  8825 D PIF/Native: Read 425 bytes of pif.json
02-12 13:09:02.524  8825  8825 D PIF/Native: JSON contains 13 keys!
02-12 13:09:02.524  8825  8825 D PIF/Native: get system classloader
02-12 13:09:02.524  8825  8825 D PIF/Native: create class loader
02-12 13:09:02.525  8825  8825 D PIF/Native: load class
02-12 13:09:02.525  8825  8825 D PIF/Native: call init
02-12 13:09:02.526  8825  8825 D PIF/Java: Spoof KeyStoreSpi and Provider done!
02-12 13:09:02.526  8825  8825 D PIF/Java: [PRODUCT]: cmi -> XXXXXX
02-12 13:09:02.526  8825  8825 D PIF/Java: [DEVICE]: cmi -> XXXXXX
02-12 13:09:02.526  8825  8825 D PIF/Java: [MANUFACTURER]: Xiaomi -> XXXX
02-12 13:09:02.526  8825  8825 D PIF/Java: [BRAND]: Xiaomi -> XXXX
02-12 13:09:02.526  8825  8825 D PIF/Java: [MODEL]: Mi 10 Pro -> XXXXXXX
02-12 13:09:02.526  8825  8825 D PIF/Java: [FINGERPRINT]: Xiaomi/cmi/cmi:10/QKQ1.191117.002/V11.0.17.0.QJACNXM:user/release-keys -> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
02-12 13:09:02.526  8825  8825 D PIF/Java: [ID]: QKQ1.200419.002 -> XXXXXXXXXX
02-12 13:09:02.527  8825  8825 D PIF/Java: [SECURITY_PATCH]: 2020-04-01 -> XXXXXXXX
02-12 13:09:02.903  8825  8825 D PIF/Java: [PRODUCT]: unknown -> XXXXXXX
02-12 13:09:02.903  8825  8825 D PIF/Java: [DEVICE]: unknown -> XXXXXXXX
02-12 13:09:02.903  8825  8825 D PIF/Java: [MANUFACTURER]: unknown -> XXXX
02-12 13:09:02.903  8825  8825 D PIF/Java: [BRAND]: unknown -> XXXXXX
02-12 13:09:02.903  8825  8825 D PIF/Java: [MODEL]: unknown -> XXXXXXXXX
02-12 13:09:02.903  8825  8825 D PIF/Java: [ID]: unknown -> XXXXXX
02-12 13:09:03.583  8825  8870 D PIF/Native: [ro.build.version.security_patch]: XXXXXXXXX
02-12 13:09:03.770  8825  8925 D PIF/Java: DroidGuard detected!
02-12 13:09:03.932  8825  8925 D PIF/Java: DroidGuard detected!
02-12 13:09:03.933  8825  8925 D PIF/Native: [ro.build.version.security_patch]: XXXXXXXXX
02-12 13:09:05.968  8825  9103 D PIF/Native: [ro.build.version.security_patch]: XXXXXXXXX
02-12 13:09:19.540  8825  8871 D PIF/Java: DroidGuard detected!
02-12 13:09:19.790  8825  8871 D PIF/Java: DroidGuard detected!
02-12 13:09:19.796  8825  8871 D PIF/Native: [ro.build.version.security_patch]: XXXXXXXXX
02-12 13:09:46.244 13611 13611 D PIF/Native: Found '__system_property_read_callback' handle at 0x7828de3e20
02-12 13:09:46.244 13611 13611 D PIF/Native: Read 7072 bytes of classes.dex
02-12 13:09:46.244 13611 13611 D PIF/Native: Read 425 bytes of pif.json
02-12 13:09:46.244 13611 13611 D PIF/Native: JSON contains 13 keys!
02-12 13:09:46.244 13611 13611 D PIF/Native: get system classloader
02-12 13:09:46.244 13611 13611 D PIF/Native: create class loader
02-12 13:09:46.244 13611 13611 D PIF/Native: load class
02-12 13:09:46.244 13611 13611 D PIF/Native: call init
02-12 13:09:46.245 13611 13611 D PIF/Java: Spoof KeyStoreSpi and Provider done!
02-12 13:09:46.245 13611 13611 D PIF/Java: [PRODUCT]: cmi -> XXXXXXXXX
02-12 13:09:46.245 13611 13611 D PIF/Java: [DEVICE]: cmi -> XXXXXXXXX
02-12 13:09:46.245 13611 13611 D PIF/Java: [MANUFACTURER]: Xiaomi -> XXXXXXXXX
02-12 13:09:46.246 13611 13611 D PIF/Java: [BRAND]: Xiaomi -> XXXXXXXXX
02-12 13:09:46.246 13611 13611 D PIF/Java: [MODEL]: Mi 10 Pro -> XXXXXXXXX
02-12 13:09:46.246 13611 13611 D PIF/Java: [FINGERPRINT]: Xiaomi/cmi/cmi:10/QKQ1.191117.002/V11.0.17.0.QJACNXM:user/release-keys -> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
02-12 13:09:46.246 13611 13611 D PIF/Java: [ID]: QKQ1.200419.002 -> XXXXXXXXX
02-12 13:09:46.246 13611 13611 D PIF/Java: [SECURITY_PATCH]: 2020-04-01 -> XXXXXXXXX
02-12 13:09:49.049 13611 13643 D PIF/Native: [ro.build.version.security_patch]: XXXXXXXXX
02-12 13:09:49.486 13611 13829 D PIF/Java: DroidGuard detected!
02-12 13:09:50.774 13611 13829 D PIF/Native: [ro.build.version.security_patch]: XXXXXXXXX
02-12 13:09:51.052 13611 13829 D PIF/Java: DroidGuard detected!`

The only different thing I can think of it could be different is my Android version (10).

Thanks in advance.

**Comment by MaccabeeY** [comment]
Yeah, seems we're in a "fluid" situation.  Today, I saw that I no longer passed DEVICE_INTEGRITY with my configuration that worked just a few days ago.

After some research in @chiteroman /PlayIntegrityFix issues section and some tideous trial & error I discovered a configuration that passes both BASIC & DEVICE_INTEGRITY, at least as of now.

For context, as of this evening, I'm currently successfully passing BASIC & DEVICE running on a Pixel 5 GD1YQ with the following: LineageOS 20.0 (dated 20240129); Magisk canary 26404; Play Integrity Fix 15.7.1 (NO pif.jason in /data/adb); Shamiko 1.0.1; LSPosed 1.9.2; BootloaderSpoofer 1.2; Hide My Applist 3.2

The one thing I think I noticed was that Play Store would not run "correctly" right away, kept getting "Try Again".
To get Play Store to run right, seems I had to play around clearing cache & data for Play Store, Play Services, & Google Services Framework - rebooting; rinse & repeat.  It also seemed to help by keeping an eye on the "Manage Space" for Play Services to try to tell when the its storage stopped growing.

Hope this can be useful.

**Comment by pmsobrado** [comment]
@MaccabeeY you mean you are passing BASIC + DEVICE without custom FP?

**Comment by MaccabeeY** [comment]
> @MaccabeeY you mean you are passing BASIC + DEVICE without custom FP?

Yes, correct...just the FP provided by @chiteroman /PlayIntegrityFix v15.7.1.

**Comment by pmsobrado** [comment]
@MaccabeeY I did not know 15.7.1 had an FP... the more you know.
