### ISSUE TITLE
Only basic integrity

### ISSUE THREAD

**Issue by VaporeonScripts** [chiteroman/PlayIntegrityFix#409]
![Screenshot_20240821-101558_Play Integrity API Checker](https://github.com/user-attachments/assets/f7075fb8-b191-4c74-9da4-3f92911f0cce)
17.2

**Comment by Delitants** [comment]
Confirming, it stopped working.

**Comment by Delitants** [comment]
![image](https://github.com/user-attachments/assets/fa23d061-0356-49b6-8fd2-2ce26315c9fa)
Now this

**Comment by LionTVVV** [comment]
> ![image](https://private-user-images.githubusercontent.com/2836790/360720200-fa23d061-0356-49b6-8fd2-2ce26315c9fa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTIzODYsIm5iZiI6MTcyNDQxMjA4NiwicGF0aCI6Ii8yODM2NzkwLzM2MDcyMDIwMC1mYTIzZDA2MS0wMzU2LTQ5YjYtOGZkMi0yY2UyNjMxNWM5ZmEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTEyMTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI5MDBjOWRkZTA1MDBiNzg1ZmExNjBkNmE0MTg1ZGU4MWY4YWZlNjU5N2YyZDRiZGE2OTAxMmQ4MTAxNDAxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gXfwjoxouMB6Qa65cXzOpNP8yqHD3J6NWiqJCIoAXuw) Now this

You checked it to many times and Google is blocking you.

**Comment by MrITKid** [comment]
It stopped working for me too... Hoping for a fix too I need my RCS

![Screenshot_2024-08-23-18-43-50-09_c164fb607f41c6d3a88bed2bf1a99c07](https://github.com/user-attachments/assets/6ed08c4f-6fef-492a-bcbc-dd67fa4370e0)

**Comment by MrITkid** [comment]
> It stopped working for me too... Hoping for a fix too I need my RCS
> 
> ![Screenshot_2024-08-23-18-43-50-09_c164fb607f41c6d3a88bed2bf1a99c07](https://private-user-images.githubusercontent.com/92473802/360986331-6ed08c4f-6fef-492a-bcbc-dd67fa4370e0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzE2MTcsIm5iZiI6MTcyNDQzMTMxNywicGF0aCI6Ii85MjQ3MzgwMi8zNjA5ODYzMzEtNmVkMDhjNGYtNmZlZi00OTJhLWJjYmMtZGQ2N2ZhNDM3MGUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE2NDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYWFhOWJhZmRiMjNiNTczNTlkOTgzYmZhOTkwZDY5ZjJiM2YyZmIzMmY2MzM3ZGMxYTY2MDYxMzZmOWRkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ViGuYUWmnyhRC3gaDiut3_fA3T8elTFiGeUlHQAJKaw)

A remove and re-add of the module temporarily fixed it for me, hope this helps others 👍

![Screenshot_2024-08-23-19-40-14-97_c164fb607f41c6d3a88bed2bf1a99c07](https://github.com/user-attachments/assets/70e3eb0f-121e-4381-bc16-f97534255361)

**Comment by Delitants** [comment]
> > It stopped working for me too... Hoping for a fix too I need my RCS
> > ![Screenshot_2024-08-23-18-43-50-09_c164fb607f41c6d3a88bed2bf1a99c07](https://private-user-images.githubusercontent.com/92473802/360986331-6ed08c4f-6fef-492a-bcbc-dd67fa4370e0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzE2MTcsIm5iZiI6MTcyNDQzMTMxNywicGF0aCI6Ii85MjQ3MzgwMi8zNjA5ODYzMzEtNmVkMDhjNGYtNmZlZi00OTJhLWJjYmMtZGQ2N2ZhNDM3MGUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE2NDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYWFhOWJhZmRiMjNiNTczNTlkOTgzYmZhOTkwZDY5ZjJiM2YyZmIzMmY2MzM3ZGMxYTY2MDYxMzZmOWRkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ViGuYUWmnyhRC3gaDiut3_fA3T8elTFiGeUlHQAJKaw)
> 
> A remove and re-add of the module temporarily fixed it for me, hope this helps others 👍
> 
> ![Screenshot_2024-08-23-19-40-14-97_c164fb607f41c6d3a88bed2bf1a99c07](https://private-user-images.githubusercontent.com/92473802/361001600-70e3eb0f-121e-4381-bc16-f97534255361.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzMwNzUsIm5iZiI6MTcyNDQzMjc3NSwicGF0aCI6Ii85MjQ3MzgwMi8zNjEwMDE2MDAtNzBlM2ViMGYtMTIxZS00MzgxLWJjMTYtZjk3NTM0MjU1MzYxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE3MDYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZDQ0NjUwMmYwZTFiMmZmNWY5ZDkxM2UyOTg1ODk3NTkyYjBiNmE3YjI3NGY5M2ViN2EwNDRiMWY3YzkwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NRdYgDKlj1Db9CZef144lsEW9BUTPSU3TkGO0EAAg8A)

does not help

**Comment by VaporeonScripts** [comment]
with 17.3 the issue was fixed,i may close this issue now.

**Comment by bphd** [comment]
> A remove and re-add of the module temporarily

What do you mean? Uninstallation of PIF then immediate reinstallation without any reboot? What does mean temporarily? 

> with 17.3 the issue was fixed

Still happens in 176

**Comment by VaporeonScripts** [comment]
I can't confirm right now,as the API Checker reached the 10k uses

**Comment by bphd** [comment]
By deactivating `persist.sys.pixelprops.gapps` `persist.sys.pixelprops.gms` properties and resintalling vending/gsf/gms and spoofing build and provider (and btw using that module, or Osm0sis one when that one bother me) I achieve device integrity. I have difficulties achieving strong integrity but it's probably because my CROM throw `UnsupportedOperationException()` when DroidGuard ask for certificate chain, have to figure out how to patch from MagiSK, or LSP, or by replacing files
